name: Build

on:
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels for ${{ matrix.python[0] }}-${{ matrix.buildplat[1] }}
    runs-on: ${{ matrix.buildplat[0] }}
    strategy:
      fail-fast: false
      matrix:
        buildplat:
        - [ubuntu-24.04, manylinux_x86_64]
#        - [ubuntu-24.04, musllinux_x86_64]
#        - [ubuntu-24.04-arm, manylinux_aarch64]
#        - [ubuntu-24.04-arm, musllinux_aarch64]
#        - [macos-15-intel, macosx_x86_64]
#        - [macos-15, macosx_arm64]
#        - [windows-2025, win_amd64]
#        - [windows-11-arm, win_arm64]
        python: [["cp311", "3.11"], ]

    steps:
      - name: Checkout mapflpy
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python[1] }}
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      # Install gfortran on each OS
      - name: Setup Fortran Compiler
        uses: fortran-lang/setup-fortran@v1
        id: setup-fortran
        with:
            compiler: gcc
            version: 13

      - name: Build wheels
        uses: pypa/cibuildwheel@9c00cb4f6b517705a3794b22395aedc36257242c
        env:
          CIBW_BUILD: ${{ matrix.python[0] }}-${{ matrix.buildplat[1] }}
          CIBW_BEFORE_BUILD: |
            yum -y install gcc-gfortran gcc-c++ make tar gzip xz zlib-devel libaec-devel
            HDF5_VER=1.12.3
            curl -fsSL https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-${HDF5_VER%.*}/hdf5-$HDF5_VER/src/hdf5-$HDF5_VER.tar.gz \
              | tar xz
            cd hdf5-$HDF5_VER
            ./configure --prefix=/opt/hdf5 --enable-fortran --disable-static --enable-build-mode=production \
              --with-zlib=/usr --without-szlib
            make -j"$(nproc)"
            make install
            cd ..

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.python[0] }}-${{ matrix.buildplat[1] }}-${{ matrix.buildplat[2] }}
          path: ./wheelhouse/*.whl